version: '3'
services:
  app:
    depends_on:
      - bd
    image: romulonishiyama/crud:v1    
    ports:
      - 8080:8080
  
 
  bd:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
    ports:
      - 3306:3306
    volumes:
      - ./volumes:/var/lib/mysql
   
